### ISSUE TITLE
some float fields are getting nan for their values

### ISSUE THREAD

**Issue by mmguero** [cisagov/icsnpp-hart-ip#12]
In the hart_ip_universal_commands.log field for the hart-ip.pcap file in your traces directory:

* read_dynamic_variable_response_primary_variable_loop_current
* read_loop_current_response_primary_variable_loop_current

return a `nan` value sometimes. This will make it so opensearch is unable to parse these values (as they're not floats). I could ignore them on my side, but it'll be better if you fix it at the source.

**Comment by piercema** [comment]
NaN is actually the correct value as shown and passed in the protocol. Zeek accepts this as a valid float value.

![image](https://github.com/user-attachments/assets/fb965c80-4e8c-41af-b1ba-779417f6e430)
