### ISSUE TITLE
some IP addresses may be in the wrong byte order

### ISSUE THREAD

**Issue by mmguero** [cisagov/icsnpp-hart-ip#13]
`zeek.hart_ip_session_record.session_log_record_client_i_pv4_address` from the hartip_all_messageIDs.pcap file has an IP address like `144.0.9.10`. In this case, I'm almost certain the address is actually `10.9.0.144` and needs to have its byte order reversed.

This should be checked for both IPv4 addresses in `zeek.hart_ip_session_record.session_log_record_client_i_pv4_address` and ipv6 addresses in `zeek.hart_ip_session_record.session_log_record_client_i_pv6_address`.

**Comment by mmguero** [comment]
EDIT: after some review, this may not be a problem in the parser, but it may be a problem with bad PCAP data. We don't know for sure, though, and I don't think can really close this until we've identified some valid PCAP data to see what's correct.

**Comment by nagilum2007** [comment]
After review, this is a confirmed bug in the HART-IP implementation used by the device used to generate the test data. We will update the test data if/when better data becomes available.
